title: Gurklang Language Reference
email: doublevcodes@gmail.com
description: >-
  How to Gurklang right
baseurl: "/gurklang-spec"
url: "https://doublevcodes.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_user_name: doublevcodes

remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
plugins:
  - jekyll-feed

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

aux_links:
  "Gurkult": https://gurkult.com
aux_links_new_tab: true

color_scheme: dark

collections:
  general:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    general:
      name: General

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
